//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiBuBlog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public string CategoryId { get; set; }
        public string TargetUrl { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public byte Sort { get; set; }
        public byte IsFront { get; set; }
        public byte Status { get; set; }
    }
}
