//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiBuBlog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public byte CanSetGlobal { get; set; }
        public byte CanReview { get; set; }
        public byte ArticleLimit { get; set; }
        public byte MaxArticleWeight { get; set; }
        public byte CanManageUser { get; set; }
        public byte IsAdmin { get; set; }
    }
}
