//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiBuBlog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string GroupId { get; set; }
        public string Nickname { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string HomePage { get; set; }
        public System.DateTime RegTime { get; set; }
        public string LastIP { get; set; }
        public System.DateTime LastActivity { get; set; }
    }
}
