//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiBuBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public byte IsOpen { get; set; }
        public string CloseReason { get; set; }
        public string SiteName { get; set; }
        public string SiteDomain { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string ForbiddenIP { get; set; }
        public double TimeZone { get; set; }
        public byte CommentLimit { get; set; }
        public byte MinCommentSize { get; set; }
        public short MaxCommentSize { get; set; }
        public byte CommentInterval { get; set; }
    }
}
